<?php

    if(isset($_SESSION['email']) && $_SESSION['email'] == $email) {
        session_start();
        header ('location: content.phtml');
    } else {
        header ('location: login.html');
    }
    ?>

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Conteudo</title>
</head>
<body>
    <h1>Pagina Inicial</h1>
    <p> Bem vindo!</p>
    
</body>
</html>